"""
ShipRule CDLP - Query API Route
================================
Provides RAG pipeline querying with grounded answers, guardrail evaluation, and citations.
"""

from typing import List, Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Header, status as http_status
from pydantic import BaseModel, Field

from app.core.logging import logger
from app.rag.pipeline import answer_query

router = APIRouter()

class QueryRequest(BaseModel):
    """Input payload for RAG query requests with strict length validation."""
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="The question to be answered by the RAG system."
    )
    use_reranking: Optional[bool] = Field(
        default=True,
        description="Enable cross-encoder re-ranking stage."
    )
    final_k: Optional[int] = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of Top-K context chunks to retrieve."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What shipping documentation is required for international customs clearance?",
                "use_reranking": True,
                "final_k": 3
            }
        }
    }


class Source(BaseModel):
    """Source reference detail backing a RAG answer claim."""
    source: str = Field(..., description="Document source filename.")
    chunk_id: Optional[str] = Field(default=None, description="Unique chunk or document identifier.")
    score: Optional[float] = Field(default=None, description="Retrieval similarity or re-rank score.")


class QueryResponse(BaseModel):
    """Structured JSON response returned to frontend or client applications."""
    answer: str = Field(..., description="Grounded answer text generated by RAG system.")
    sources: List[Source] = Field(default_factory=list, description="List of cited source documents.")
    status: str = Field(..., description="Status code: 'answered', 'refused', or 'error'.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Timing and token usage metadata.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "answer": "International shipments require a commercial invoice and packing list [Source: shipping_rules.txt].",
                "sources": [
                    {
                        "source": "shipping_rules.txt",
                        "chunk_id": "shipping_rules.txt:1",
                        "score": 0.84
                    }
                ],
                "status": "answered",
                "metadata": {
                    "token_usage": {"input_tokens": 420, "output_tokens": 45, "total_tokens": 465},
                    "timing_ms": 1250.5
                }
            }
        }
    }


@router.post("/query", response_model=QueryResponse, tags=["RAG Pipeline"])
def query_rag(
    request: QueryRequest,
    authorization: Optional[str] = Header(None, alias="Authorization")
):
    """
    Query endpoint that accepts a user question, runs the RAG pipeline,
    and returns a grounded answer with structured source citations.
    """
    logger.info(f"Received API query request: {request.question}")

    # Determine caller user email if token present
    user_email = "registered_user"
    if authorization and authorization.startswith("Bearer "):
        token = authorization.split(" ", 1)[1]
        from app.api.dependencies import decode_access_token
        payload = decode_access_token(token)
        if payload and payload.get("email"):
            user_email = payload["email"]

    if not request.question or not request.question.strip():
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Question field cannot be empty or whitespace only."
        )

    try:
        pipeline_result = answer_query(
            query=request.question.strip(),
            final_k=request.final_k or 3,
            use_reranking=request.use_reranking if request.use_reranking is not None else True
        )
    except ValueError as val_err:
        logger.warning(f"Invalid input parameter error: {val_err}")
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except Exception as exc:
        logger.error(f"RAG pipeline execution failed: {exc}", exc_info=True)
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="RAG service failed"
        )

    answer_text = pipeline_result.get("answer", "")
    retrieved_chunks = pipeline_result.get("retrieved_chunks", [])
    guardrail_decision = pipeline_result.get("guardrail_decision", "ALLOW")

    sources_list: List[Source] = []
    seen_sources = set()

    for chunk in retrieved_chunks:
        src_name = chunk.get("source", "unknown")
        chunk_idx = chunk.get("chunk_index", 1)
        chunk_id = chunk.get("document_id") or f"{src_name}:{chunk_idx}"
        score = chunk.get("rerank_score", chunk.get("similarity_score", 0.0))

        if chunk_id not in seen_sources:
            seen_sources.add(chunk_id)
            sources_list.append(Source(
                source=src_name,
                chunk_id=chunk_id,
                score=round(float(score), 4) if score is not None else None
            ))

    guardrail_info = pipeline_result.get("guardrail", {})
    guardrail_reason = guardrail_info.get("reason")

    if guardrail_decision == "BLOCK" or guardrail_reason in ("jailbreak_attempt", "prompt_injection"):
        status_str = "SECURITY_BLOCKED"
    elif guardrail_reason == "out_of_scope":
        status_str = "OUT_OF_SCOPE"
    elif not guardrail_info.get("is_sufficient", True) or "insufficient" in answer_text.lower() or "cannot answer" in answer_text.lower():
        status_str = "INSUFFICIENT_CONTEXT"
    elif guardrail_decision == "REFUSE":
        status_str = "INSUFFICIENT_CONTEXT"
    else:
        status_str = "SUPPORTED"

    timing_info = pipeline_result.get("timing", {})
    latency_ms = timing_info.get("total_pipeline_time_ms", 0.0)

    token_usage = pipeline_result.get("token_usage", {})
    prompt_tokens = token_usage.get("prompt_tokens", 0) or token_usage.get("prompt_eval_count", 0)
    completion_tokens = token_usage.get("completion_tokens", 0) or token_usage.get("eval_count", 0)
    total_tokens = token_usage.get("total_tokens", 0) or (prompt_tokens + completion_tokens)

    if total_tokens == 0:
        prompt_tokens = max(10, len(request.question) // 4 + 40)
        completion_tokens = max(10, len(answer_text) // 4 + 20)
        total_tokens = prompt_tokens + completion_tokens

    from app.db.mongodb import log_query_activity
    log_query_activity(
        question=request.question.strip(),
        status=status_str,
        user_email=user_email,
        latency_ms=latency_ms,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=total_tokens
    )

    metadata_dict = {
        "token_usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens
        },
        "timing": timing_info,
        "guardrail_decision": guardrail_decision
    }

    return QueryResponse(
        answer=answer_text,
        sources=sources_list,
        status=status_str,
        metadata=metadata_dict
    )
