"""
ShipRule CDLP - Backend API for the RAG Service
=================================================
Exposes the ShipRule RAG Pipeline via a FastAPI REST backend API.
Provides a stable, validated JSON contract for frontends, chatbot UIs, and external microservices.
"""

import os
import sys
import logging
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, status as http_status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Ensure project root is in sys.path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Load environment variables
load_dotenv()

from src.rag_pipeline import answer_query

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("ShipRuleAPI")

# Environment configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") or os.getenv("GROQ_API_KEY", "")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", os.getenv("EMBED_MODEL", "text-embedding-3-small"))
CHAT_MODEL = os.getenv("CHAT_MODEL", "groq/compound-mini")
VECTOR_DB_URL = os.getenv("VECTOR_DB_URL", "data/vector_db")
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "rag_chunks")

# Initialize FastAPI Application
app = FastAPI(
    title="ShipRule RAG Service API",
    description="Backend API exposing Customs Duty & Shipping Documentation RAG pipeline with grounded answers and source citations.",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ==============================================================================
# PYDANTIC REQUEST & RESPONSE SCHEMAS
# ==============================================================================

class QueryRequest(BaseModel):
    """Input payload for RAG query requests with strict length validation."""
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="The question to be answered by the RAG system."
    )
    use_reranking: Optional[bool] = Field(
        default=True,
        description="Enable cross-encoder re-ranking stage."
    )
    final_k: Optional[int] = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of Top-K context chunks to retrieve."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What shipping documentation is required for international customs clearance?",
                "use_reranking": True,
                "final_k": 3
            }
        }
    }


class Source(BaseModel):
    """Source reference detail backing a RAG answer claim."""
    source: str = Field(..., description="Document source filename.")
    chunk_id: Optional[str] = Field(default=None, description="Unique chunk or document identifier.")
    score: Optional[float] = Field(default=None, description="Retrieval similarity or re-rank score.")


class QueryResponse(BaseModel):
    """Structured JSON response returned to frontend or client applications."""
    answer: str = Field(..., description="Grounded answer text generated by RAG system.")
    sources: List[Source] = Field(default_factory=list, description="List of cited source documents.")
    status: str = Field(..., description="Status code: 'answered', 'refused', or 'error'.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Timing and token usage metadata.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "answer": "International shipments require a commercial invoice and packing list [Source: shipping_rules.txt].",
                "sources": [
                    {
                        "source": "shipping_rules.txt",
                        "chunk_id": "shipping_rules.txt:1",
                        "score": 0.84
                    }
                ],
                "status": "answered",
                "metadata": {
                    "token_usage": {"input_tokens": 420, "output_tokens": 45, "total_tokens": 465},
                    "timing_ms": 1250.5
                }
            }
        }
    }


# ==============================================================================
# ENDPOINTS
# ==============================================================================

@app.get("/", tags=["System"])
def root():
    """Root endpoint returning API metadata and health status."""
    return {
        "service": "ShipRule RAG Service API",
        "status": "online",
        "version": "1.0.0",
        "config": {
            "embedding_model": EMBEDDING_MODEL,
            "chat_model": CHAT_MODEL,
            "collection_name": COLLECTION_NAME
        }
    }


@app.get("/health", tags=["System"])
def health_check():
    """Health check endpoint to verify backend API service operational state."""
    return {
        "status": "healthy",
        "service": "ShipRule RAG API",
        "environment": {
            "embedding_model_configured": bool(EMBEDDING_MODEL),
            "chat_model_configured": bool(CHAT_MODEL),
            "vector_db_path": VECTOR_DB_URL,
            "collection_name": COLLECTION_NAME
        }
    }


@app.post("/query", response_model=QueryResponse, tags=["RAG Pipeline"])
def query_rag(request: QueryRequest):
    """
    Query endpoint that accepts a user question, runs the RAG pipeline,
    and returns a grounded answer with structured source citations.
    """
    logger.info(f"Received API query request: {request.question}")

    # Validate input parameter bounds
    if not request.question or not request.question.strip():
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Question field cannot be empty or whitespace only."
        )

    try:
        pipeline_result = answer_query(
            query=request.question.strip(),
            final_k=request.final_k or 3,
            use_reranking=request.use_reranking if request.use_reranking is not None else True
        )
    except ValueError as val_err:
        logger.warning(f"Invalid input parameter error: {val_err}")
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except Exception as exc:
        logger.error(f"RAG pipeline execution failed: {exc}", exc_info=True)
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="RAG service failed"
        )

    answer_text = pipeline_result.get("answer", "")
    retrieved_chunks = pipeline_result.get("retrieved_chunks", [])
    guardrail_decision = pipeline_result.get("guardrail_decision", "ALLOW")

    # Format sources list
    sources_list: List[Source] = []
    seen_sources = set()

    for chunk in retrieved_chunks:
        src_name = chunk.get("source", "unknown")
        chunk_idx = chunk.get("chunk_index", 1)
        chunk_id = chunk.get("document_id") or f"{src_name}:{chunk_idx}"
        score = chunk.get("rerank_score", chunk.get("similarity_score", 0.0))

        if chunk_id not in seen_sources:
            seen_sources.add(chunk_id)
            sources_list.append(Source(
                source=src_name,
                chunk_id=chunk_id,
                score=round(float(score), 4) if score is not None else None
            ))

    # Determine status
    if "insufficient" in answer_text.lower() or "cannot answer" in answer_text.lower() or guardrail_decision == "REFUSE":
        status_str = "refused"
    else:
        status_str = "answered"

    metadata_dict = {
        "token_usage": pipeline_result.get("token_usage", {}),
        "timing": pipeline_result.get("timing", {}),
        "guardrail_decision": guardrail_decision
    }

    return QueryResponse(
        answer=answer_text,
        sources=sources_list,
        status=status_str,
        metadata=metadata_dict
    )
