"""
ShipRule CDLP - Backend API for the RAG Service
=================================================
Exposes the ShipRule RAG Pipeline via a FastAPI REST backend API.
Provides a stable, validated JSON contract for frontends, chatbot UIs, and external microservices.
"""

import os
import sys
import re
import uuid
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

from fastapi import FastAPI, HTTPException, UploadFile, File, status as http_status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Ensure project root is in sys.path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Load environment variables
load_dotenv()

from src.rag_pipeline import answer_query
from src.text_cleaner import clean
from src.document_loader import token_chunks, _load_pdf
from src.embeddings import create_embedding_client, generate_embedding

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("ShipRuleAPI")

# Environment configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") or os.getenv("GROQ_API_KEY", "")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", os.getenv("EMBED_MODEL", "text-embedding-3-small"))
CHAT_MODEL = os.getenv("CHAT_MODEL", "groq/compound-mini")
VECTOR_DB_URL = os.getenv("VECTOR_DB_URL", "data/vector_db")
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "rag_chunks")
MAX_UPLOAD_SIZE_MB = int(os.getenv("MAX_UPLOAD_SIZE_MB", "10"))
SUPPORTED_EXTENSIONS = {".txt", ".md", ".pdf"}

# Initialize FastAPI Application
app = FastAPI(
    title="ShipRule RAG Service API",
    description="Backend API exposing Customs Duty & Shipping Documentation RAG pipeline with grounded answers and source citations.",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ==============================================================================
# PYDANTIC REQUEST & RESPONSE SCHEMAS
# ==============================================================================

class QueryRequest(BaseModel):
    """Input payload for RAG query requests with strict length validation."""
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="The question to be answered by the RAG system."
    )
    use_reranking: Optional[bool] = Field(
        default=True,
        description="Enable cross-encoder re-ranking stage."
    )
    final_k: Optional[int] = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of Top-K context chunks to retrieve."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What shipping documentation is required for international customs clearance?",
                "use_reranking": True,
                "final_k": 3
            }
        }
    }


class Source(BaseModel):
    """Source reference detail backing a RAG answer claim."""
    source: str = Field(..., description="Document source filename.")
    chunk_id: Optional[str] = Field(default=None, description="Unique chunk or document identifier.")
    score: Optional[float] = Field(default=None, description="Retrieval similarity or re-rank score.")


class QueryResponse(BaseModel):
    """Structured JSON response returned to frontend or client applications."""
    answer: str = Field(..., description="Grounded answer text generated by RAG system.")
    sources: List[Source] = Field(default_factory=list, description="List of cited source documents.")
    status: str = Field(..., description="Status code: 'answered', 'refused', or 'error'.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Timing and token usage metadata.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "answer": "International shipments require a commercial invoice and packing list [Source: shipping_rules.txt].",
                "sources": [
                    {
                        "source": "shipping_rules.txt",
                        "chunk_id": "shipping_rules.txt:1",
                        "score": 0.84
                    }
                ],
                "status": "answered",
                "metadata": {
                    "token_usage": {"input_tokens": 420, "output_tokens": 45, "total_tokens": 465},
                    "timing_ms": 1250.5
                }
            }
        }
    }


class IndexingSummary(BaseModel):
    """Structured indexing summary for an uploaded document."""
    document: str = Field(..., description="Stored document path relative to uploads directory.")
    chunks: int = Field(..., description="Number of text chunks generated from the document.")
    indexed: int = Field(..., description="Number of vector embeddings successfully indexed.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "document": "uploads/new-policy.md",
                "chunks": 12,
                "indexed": 12
            }
        }
    }


class DocumentUploadResponse(BaseModel):
    """Response model returned following successful document upload and indexing."""
    status: str = Field(default="indexed", description="Indexing status result.")
    filename: str = Field(..., description="Original name of the uploaded document file.")
    summary: IndexingSummary = Field(..., description="Detailed indexing metrics summary.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "status": "indexed",
                "filename": "new-policy.md",
                "summary": {
                    "document": "uploads/new-policy.md",
                    "chunks": 12,
                    "indexed": 12
                }
            }
        }
    }


# ==============================================================================
# DOCUMENT PROCESSING PIPELINE HELPER
# ==============================================================================

def process_uploaded_document(file_path: Path, original_filename: str) -> Dict[str, Any]:
    """
    Extracts text, cleans, chunks, tags metadata, generates embeddings,
    and updates vector storage for an uploaded document.
    """
    ext = file_path.suffix.lower()

    # 1. Load raw text
    try:
        if ext in {".txt", ".md"}:
            with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                raw_text = f.read().strip()
        elif ext == ".pdf":
            raw_text = _load_pdf(str(file_path))
        else:
            raise ValueError(f"Unsupported file extension '{ext}'")
    except Exception as e:
        if "contains no extractable text" in str(e).lower() or isinstance(e, ValueError):
            raise ValueError("Document contains no extractable text")
        raise RuntimeError(f"Failed to read file: {e}")

    if not raw_text or not raw_text.strip():
        raise ValueError("Document contains no extractable text")

    # 2. Clean text
    cleaned_text = clean(raw_text)
    if not cleaned_text or not cleaned_text.strip():
        raise ValueError("Document contains no extractable text")

    # 3. Chunk text
    raw_token_chunks = token_chunks(cleaned_text, size=400, overlap=60)
    if not raw_token_chunks:
        raise ValueError("Document contains no extractable text")

    # 4. Attach metadata
    rel_document_path = f"uploads/{file_path.name}"
    tagged_chunks = []
    for idx, tc in enumerate(raw_token_chunks, start=1):
        chunk_text_item = tc["text"]
        page_num = "1"
        page_match = re.search(r"\[Page\s+(\d+)\]", chunk_text_item)
        if page_match:
            page_num = page_match.group(1)
            chunk_text_item = re.sub(r"\[Page\s+\d+\]\n?", "", chunk_text_item).strip()

        chunk_id = f"{file_path.name}_chunk_{idx}"
        emb_id = f"emb_{file_path.name}_{idx:03d}"

        tagged_chunks.append({
            "id": chunk_id,
            "chunk_id": chunk_id,
            "embedding_id": emb_id,
            "source": rel_document_path,
            "filename": original_filename,
            "chunk_index": idx,
            "document_type": ext.lstrip("."),
            "strategy": "token",
            "page": str(page_num),
            "chunk_text": chunk_text_item,
            "character_count": len(chunk_text_item),
            "token_count": tc.get("token_count", 0),
            "metadata": {
                "source": rel_document_path,
                "filename": original_filename,
                "chunk_index": idx,
                "page": str(page_num),
                "document_type": ext.lstrip("."),
                "chunk_id": chunk_id,
                "strategy": "token"
            }
        })

    # 5. Generate embeddings
    client = create_embedding_client()
    embedded_chunks = []
    for item in tagged_chunks:
        vec = generate_embedding(client, item["chunk_text"], model=EMBEDDING_MODEL)
        item["embedding"] = vec
        item["vector"] = vec
        item["vector_dimension"] = len(vec)
        item["embedding_model"] = EMBEDDING_MODEL
        embedded_chunks.append(item)

    # 6. Index into outputs/embedded_chunks.json
    outputs_dir = Path(project_root) / "outputs"
    outputs_dir.mkdir(parents=True, exist_ok=True)
    embedded_chunks_file = outputs_dir / "embedded_chunks.json"

    existing_chunks = []
    if embedded_chunks_file.exists():
        try:
            with open(embedded_chunks_file, "r", encoding="utf-8") as f:
                existing_chunks = json.load(f)
                if not isinstance(existing_chunks, list):
                    existing_chunks = []
        except Exception:
            existing_chunks = []

    new_ids = {c["id"] for c in embedded_chunks}
    updated_list = [c for c in existing_chunks if c.get("id") not in new_ids]
    updated_list.extend(embedded_chunks)

    with open(embedded_chunks_file, "w", encoding="utf-8") as f:
        json.dump(updated_list, f, indent=2, ensure_ascii=False)

    return {
        "document": rel_document_path,
        "chunks": len(tagged_chunks),
        "indexed": len(embedded_chunks)
    }


# ==============================================================================
# ENDPOINTS
# ==============================================================================

@app.get("/", tags=["System"])
def root():
    """Root endpoint returning API metadata and health status."""
    return {
        "service": "ShipRule RAG Service API",
        "status": "online",
        "version": "1.0.0",
        "config": {
            "embedding_model": EMBEDDING_MODEL,
            "chat_model": CHAT_MODEL,
            "collection_name": COLLECTION_NAME
        }
    }


@app.get("/health", tags=["System"])
def health_check():
    """Health check endpoint to verify backend API service operational state."""
    return {
        "status": "healthy",
        "service": "ShipRule RAG API",
        "environment": {
            "embedding_model_configured": bool(EMBEDDING_MODEL),
            "chat_model_configured": bool(CHAT_MODEL),
            "vector_db_path": VECTOR_DB_URL,
            "collection_name": COLLECTION_NAME,
            "max_upload_size_mb": MAX_UPLOAD_SIZE_MB
        }
    }


@app.post("/query", response_model=QueryResponse, tags=["RAG Pipeline"])
def query_rag(request: QueryRequest):
    """
    Query endpoint that accepts a user question, runs the RAG pipeline,
    and returns a grounded answer with structured source citations.
    """
    logger.info(f"Received API query request: {request.question}")

    # Validate input parameter bounds
    if not request.question or not request.question.strip():
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Question field cannot be empty or whitespace only."
        )

    try:
        pipeline_result = answer_query(
            query=request.question.strip(),
            final_k=request.final_k or 3,
            use_reranking=request.use_reranking if request.use_reranking is not None else True
        )
    except ValueError as val_err:
        logger.warning(f"Invalid input parameter error: {val_err}")
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except Exception as exc:
        logger.error(f"RAG pipeline execution failed: {exc}", exc_info=True)
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="RAG service failed"
        )

    answer_text = pipeline_result.get("answer", "")
    retrieved_chunks = pipeline_result.get("retrieved_chunks", [])
    guardrail_decision = pipeline_result.get("guardrail_decision", "ALLOW")

    # Format sources list
    sources_list: List[Source] = []
    seen_sources = set()

    for chunk in retrieved_chunks:
        src_name = chunk.get("source", "unknown")
        chunk_idx = chunk.get("chunk_index", 1)
        chunk_id = chunk.get("document_id") or f"{src_name}:{chunk_idx}"
        score = chunk.get("rerank_score", chunk.get("similarity_score", 0.0))

        if chunk_id not in seen_sources:
            seen_sources.add(chunk_id)
            sources_list.append(Source(
                source=src_name,
                chunk_id=chunk_id,
                score=round(float(score), 4) if score is not None else None
            ))

    # Determine status
    if "insufficient" in answer_text.lower() or "cannot answer" in answer_text.lower() or guardrail_decision == "REFUSE":
        status_str = "refused"
    else:
        status_str = "answered"

    metadata_dict = {
        "token_usage": pipeline_result.get("token_usage", {}),
        "timing": pipeline_result.get("timing", {}),
        "guardrail_decision": guardrail_decision
    }

    return QueryResponse(
        answer=answer_text,
        sources=sources_list,
        status=status_str,
        metadata=metadata_dict
    )


@app.post(
    "/documents",
    response_model=DocumentUploadResponse,
    status_code=http_status.HTTP_200_OK,
    tags=["Document Management"]
)
async def upload_document(file: UploadFile = File(...)):
    """
    Uploads, validates, cleans, chunks, embeds, and indexes a .txt, .md, or .pdf document.
    Makes the uploaded document immediately searchable through the /query endpoint.
    """
    logger.info(f"Received document upload request for filename: {getattr(file, 'filename', None)}")

    # 1. Filename presence validation
    if not file or not file.filename or not file.filename.strip():
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Missing or invalid filename"
        )

    raw_filename = file.filename.strip()

    # 2. Extension validation
    ext = Path(raw_filename).suffix.lower()
    if ext not in SUPPORTED_EXTENSIONS:
        raise HTTPException(
            status_code=http_status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="Unsupported file type"
        )

    # 3. Path traversal & filename sanitization
    original_filename = Path(raw_filename).name
    if not original_filename or original_filename in (".", ".."):
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Missing or invalid filename"
        )

    # 4. Read & Size Validation
    try:
        content = await file.read()
    except Exception as exc:
        logger.error(f"Failed to read upload file stream: {exc}")
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Failed to read uploaded file"
        )

    if len(content) == 0:
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Document contains no extractable text"
        )

    if len(content) > MAX_UPLOAD_SIZE_MB * 1024 * 1024:
        raise HTTPException(
            status_code=http_status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File exceeds maximum allowed upload size of {MAX_UPLOAD_SIZE_MB}MB"
        )

    # 5. Secure File Storage under uploads/
    uploads_dir = Path(project_root) / "uploads"
    uploads_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_id = uuid.uuid4().hex[:8]
    sanitized_basename = re.sub(r"[^\w\.-]", "_", original_filename)
    stored_filename = f"{timestamp}_{unique_id}_{sanitized_basename}"
    stored_filepath = (uploads_dir / stored_filename).resolve()

    # Verify path safety to prevent path traversal outside uploads/
    if not str(stored_filepath).startswith(str(uploads_dir.resolve())):
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail="Unsafe filename or path traversal attempt"
        )

    try:
        stored_filepath.write_bytes(content)
    except Exception as exc:
        logger.error(f"Failed to write stored upload file: {exc}")
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Document indexing failed"
        )

    # 6. Processing Pipeline & Indexing
    try:
        summary_result = process_uploaded_document(stored_filepath, original_filename)
    except ValueError as val_err:
        logger.warning(f"Document extraction validation error: {val_err}")
        raise HTTPException(
            status_code=http_status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except HTTPException:
        raise
    except Exception as exc:
        logger.error(f"Document processing or indexing failed: {exc}", exc_info=True)
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Document indexing failed"
        )

    return DocumentUploadResponse(
        status="indexed",
        filename=original_filename,
        summary=IndexingSummary(
            document=summary_result["document"],
            chunks=summary_result["chunks"],
            indexed=summary_result["indexed"]
        )
    )

